[package]
name = "engine"
version = "0.1.0"
authors = ["Matthias Lochbrunner <matthias_lochbrunner@web.de>"]
edition = "2018"


[lib]
name = "engine"

[dependencies]
common = { path = "../common" }
nalgebra = "0.20"
ncollide2d = "0.22"